GET http://localhost:3000/

### SEND FETCH SONGS REQUEST
GET http://localhost:3000/songs

### FIND SONGS REQUEST
GET http://localhost:3000/songs/1

### CREATE NEW SONGS REQUEST
POST http://localhost:3000/songs

### UPDATE SONGS REQUEST
PUT http://localhost:3000/songs/1

### DELETE SONGS REQUEST
DELETE http://localhost:3000/songs/1